version: '2'

services:
    scratchpad:
        image: kiliant/scratchpad:latest
        container_name: scratchpad
        ports:
        - "22:22"
        stdin_open: true
        volumes:
        - $HOME/.ssh:/root/.ssh
        - $HOME/scratchpad:/mnt/host
