version: '2'

services:
    scratchpad:
        image: kiliant/scratchpad:latest
        container_name: scratchpad
# for debugging (e.g. with gdb) uncomment this ->
#        security_opt:
#            - seccomp:unconfined
# <-
        hostname: scratchpad
        restart: always
        ports:
        - "22:22"
        stdin_open: true
        volumes:
        - $HOME/scratchpad:/home/me/host
